---

- name: Check if Elasticsearch is installed
  command: dpkg-query -l elasticsearch
  ignore_errors: yes
  register: es_pkg_check

- name: Continuing with Elasticsearch install
  when: not es_pkg_check is succeeded
  block:
    - name: Download Elasticsearch
      get_url:
        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-amd64.deb"
        dest: "/tmp/elasticsearch-{{ elasticsearch_version }}-amd64.deb"
        checksum: sha512:https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-amd64.deb.sha512

    - name: Install Elasticsearch from deb artifact
      apt:
        deb: /tmp/elasticsearch-{{ elasticsearch_version }}-amd64.deb
        state: present
    #  register: install

    #- debug: msg="{{ install.stdout }}"

    - name: Remove downloaded Elasticsearch archive
      file:
        path: /tmp/elasticsearch-{{ elasticsearch_version }}-amd64.deb
        state: absent
