---

- name: Install required packages
  ansible.builtin.apt:
    update_cache: yes
    name: gpg
    state: present

- name: Install HashiCorp apt key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

#- name: Register distribution codename
#  command: lsb_release -sc
#  register: distro_codename

#- name: Add HashiCorp apt repository
#  ansible.builtin.apt_repository:
#    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ distro_codename.stdout }} main
#    state: present
#    filename: hashicorp

- name: Install Nomad
  ansible.builtin.apt:
    update_cache: yes
    name: nomad
    state: present

